### ISSUE TITLE
How to download the dataset

### ISSUE THREAD

**Issue by qianwangn** [csiro-robotics/deepseagrass#1]
How to download the dataset?

**Comment by peymmo** [comment]
we are working to upload the dataset. Will give you an update once it is done

**Comment by Neha-Baranwal** [comment]
What is format of dataset that it is accepting because when i am running the code on my dataset it is creating an empty .csv file.

**Comment by sgraine** [comment]
The static link to the dataset has been added.  You are able to download the dataset via that link.
