### ISSUE TITLE
Dataset Format

### ISSUE THREAD

**Issue by Neha-Baranwal** [csiro-robotics/deepseagrass#3]
What is format of dataset that it is accepting because when i am running the code on my dataset it is creating an empty .csv file.
My dataset format is 
Train
    Algae
       image 1
       image 2
       
so on...............

**Comment by peymmo** [comment]
We are just about to release our dataset and readme file to how to prepare your own datasets. Will get back to you shortly.

**Comment by Neha-Baranwal** [comment]
When we would expect your data.

**Comment by sgraine** [comment]
The static link to the dataset has been added.
